### ISSUE TITLE
Problem when I test with one sequence after training process

### ISSUE THREAD

**Issue by qicheng-ma** [Devil625/Codon_Optimization#2]
Dear Admin,

I found a problem when I test with one sequence after training process:
Traceback (most recent call last):
  File "main.py", line 465, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "main.py", line 421, in load_model_decode
    speed, acc, p, r, f, pred_results, pred_scores = evaluate(data, model, name, data.nbest)
  File "main.py", line 201, in evaluate
    acc, p, r, f = get_ner_fmeasure(gold_results, pred_results, data.tagScheme)
  File "/mnt/efs/home/stb3865/software/Codon_Optimization/utils/metric.py", line 57, in get_ner_fmeasure
    accuracy = (right_tag+0.0)/all_tag
ZeroDivisionError: float division by zero

Could you please take a look ?

Thank you!

**Comment by Devil625** [comment]
It may be a problem with read data. Check the format of the data, and you can refer to read_instance

**Comment by qicheng-ma** [comment]
Dear Admin,

The input formats are ok since it was generated from codonToBox which is the same process as the training dataset.

Could you please pick any test dataset which only contain one sequence and run the test dataset and try to see whey happens ?

Thank you.

**Comment by qicheng-ma** [comment]
Hi Admin,

This is the input, please have a test.

Thank you.

$more CPA.txt
M j
T m
C d
P m
D r
K u
P n
G p
Q r
L f
I i
N o
W k
F b
I h
C g
S f
L g
C g
V g
P n
R s
V k
R g
K u
L f
W k
S r
S r
R s
R g
P m
R q
T m
R s
R u
N o
L b
L g
L g
G s
T h
A s
C d
A n
I h
Y h
L d
G s
F b
L g
V k
S r
Q r
V k
G p
R q
A n
S b
L f
Q r
H h
G q
Q r
A s
A g
E q
K u
G p
P m
H h
R n
S r
R n
D r
T m
A n
E q
P m
S f
F b
P f
E q
I i
P l
L g
D j
G k
T m
L g
A n
P f
P m
E q
S f
Q r
G s
N i
G p
S f
T h
L g
Q r
P l
N i
V k
V k
Y h
I c
T m
L h
R n
S f
K u
R n
S r
K u
P n
A n
N i
I h
R g
G s
T m
V k
K u
P l
K u
R n
R q
K t
K u
H h
A r
V k
A r
S g
A g
A n
P m
G p
Q r
E q
A g
L d
V g
G q
P m
S f
L b
Q r
P n
Q r
E u
A s
A r
R q
E u
A g
D j
A g
V j
A r
P f
G p
Y h
A g
Q r
G q
A r
N o
L g
V d
K u
I c
G q
E q
R r
P l
W k
R q
L d
V k
R s
G k
P n
G q
V k
R r
A n
G p
G s
P m
D r
F b
L g
Q r
P l
S r
S f
R q
E q
S r
N o
I c
R q
I h
Y h
S r
E q
S r
A n
P l
S f
W k
L g
S r
K t
D j
D r
I h
R r
R u
M j
R r
L f
L d
A s
D r
S r
A r
V k
A r
G p
L f
R s
P f
V k
S f
S b
R q
S r
G q
A n
R g
L d
L g
V k
L g
E q
G p
G s
A r
P f
G s
A g
V k
L f
R n
C d
G s
P f
S r
P l
C d
G p
L b
L f
K u
Q r
P l
L d
D r
M j
S j
E q
V k
F a
A n
F b
H m
L h
D r
R q
I h
L g
G p
L f
N o
R q
T m
L g
P n
S b
V k
S r
R q
K t
A r
E q
F b
I h
Q o
D j
G s
R n
P m
C g
P l
I h
I c
L b
W k
D j
A r
S b
L c
S b
S h
A r
S j
N i
D r
T m
H h
S b
S b
V d
K u
L f
T m
W k
G q
T h
Y c
Q r
Q r
L d
L g
K t
Q r
K t
C g
W k
Q r
N i
G s
R r
V j
P l
K u
P f
E u
S g
G k
C d
T h
E u
I i
H h
H h
H h
E q
W k
S f
K u
M j
A r
L f
F a
D j
F a
L d
L c
Q r
I c
Y c
N i
R n
L c
D j
T o
N i
C g
C d
G q
F b
R u
P f
R n
K u
E u
D j
A n
C d
V j
Q r
N i
G q
L d
R q
P m
K t
C d
D j
D r
Q o
G k
S b
A s
A g
L h
A r
H m
I c
I h
Q r
R r
K u
H h
D r
P m
R q
H h
L d
V d
F a
I i
D r
N o
K u
G k
F b
F a
D r
R q
S j
E u
D j
N o
L c
N o
F b
K t
L d
L c
E u
G s
I h
K t
E q
F a
P m
A g
S b
A r
V d
S b
V d
L d
K u
S r
Q r
H m
L c
R s
Q r
K t
L b
L b
Q r
S b
L g
F a
L b
D j
K t
V k
Y c
W k
E u
S j
Q o
G q
G k
R u
Q o
G q
I c
E u
K u
L b
I h
D j
V j
I i
E u
H m
R u
A n
K t
I c
L b
I h
T m
Y c
I h
N i
A r
H m
G p
V g
K t
V j
L c
P f
M j
N i
E u
X w

(base) stb3865@Insight-hpc2>>more CPA.txt
M j
T m
C d
P m
D r
K u
P n
G p
Q r
L f
I i
N o
W k
F b
I h
C g
S f
L g
C g
V g
P n
R s
V k
R g
K u
L f
W k
S r
S r
R s
R g
P m
R q
T m
R s
R u
N o
L b
L g
L g
G s
T h
A s
C d
A n
I h
Y h
L d
G s
F b
L g
V k
S r
Q r
V k
G p
R q
A n
S b
L f
Q r
H h
G q
Q r
A s
A g
E q
K u
G p
P m
H h
R n
S r
R n
D r
T m
A n
E q
P m
S f
F b
P f
E q
I i
P l
L g
D j
G k
T m
L g
A n
P f
P m
E q
S f
Q r
G s
N i
G p
S f
T h
L g
Q r
P l
N i
V k
V k
Y h
I c
T m
L h
R n
S f
K u
R n
S r
K u
P n
A n
N i
I h
R g
G s
T m
V k
K u
P l
K u
R n
R q
K t
K u
H h
A r
V k
A r
S g
A g
A n
P m
G p
Q r
E q
A g
L d
V g
G q
P m
S f
L b
Q r
P n
Q r
E u
A s
A r
R q
E u
A g
D j
A g
V j
A r
P f
G p
Y h
A g
Q r
G q
A r
N o
L g
V d
K u
I c
G q
E q
R r
P l
W k
R q
L d
V k
R s
G k
P n
G q
V k
R r
A n
G p
G s
P m
D r
F b
L g
Q r
P l
S r
S f
R q
E q
S r
N o
I c
R q
I h
Y h
S r
E q
S r
A n
P l
S f
W k
L g
S r
K t
D j
D r
I h
R r
R u
M j
R r
L f
L d
A s
D r
S r
A r
V k
A r
G p
L f
R s
P f
V k
S f
S b
R q
S r
G q
A n
R g
L d
L g
V k
L g
E q
G p
G s
A r
P f
G s
A g
V k
L f
R n
C d
G s
P f
S r
P l
C d
G p
L b
L f
K u
Q r
P l
L d
D r
M j
S j
E q
V k
F a
A n
F b
H m
L h
D r
R q
I h
L g
G p
L f
N o
R q
T m
L g
P n
S b
V k
S r
R q
K t
A r
E q
F b
I h
Q o
D j
G s
R n
P m
C g
P l
I h
I c
L b
W k
D j
A r
S b
L c
S b
S h
A r
S j
N i
D r
T m
H h
S b
S b
V d
K u
L f
T m
W k
G q
T h
Y c
Q r
Q r
L d
L g
K t
Q r
K t
C g
W k
Q r
N i
G s
R r
V j
P l
K u
P f
E u
S g
G k
C d
T h
E u
I i
H h
H h
H h
E q
W k
S f
K u
M j
A r
L f
F a
D j
F a
L d
L c
Q r
I c
Y c
N i
R n
L c
D j
T o
N i
C g
C d
G q
F b
R u
P f
R n
K u
E u
D j
A n
C d
V j
Q r
N i
G q
L d
R q
P m
K t
C d
D j
D r
Q o
G k
S b
A s
A g
L h
A r
H m
I c
I h
Q r
R r
K u
H h
D r
P m
R q
H h
L d
V d
F a
I i
D r
N o
K u
G k
F b
F a
D r
R q
S j
E u
D j
N o
L c
N o
F b
K t
L d
L c
E u
G s
I h
K t
E q
F a
P m
A g
S b
A r
V d
S b
V d
L d
K u
S r
Q r
H m
L c
R s
Q r
K t
L b
L b
Q r
S b
L g
F a
L b
D j
K t
V k
Y c
W k
E u
S j
Q o
G q
G k
R u
Q o
G q
I c
E u
K u
L b
I h
D j
V j
I i
E u
H m
R u
A n
K t
I c
L b
I h
T m
Y c
I h
N i
A r
H m
G p
V g
K t
V j
L c
P f
M j
N i
E u
X w

**Comment by Devil625** [comment]
I tried this sequence last night, and the above problem does occur. Wait for the weekend to check and fix it

**Comment by qicheng-ma** [comment]
Hi Admin,
Thank you for looking into this problem!

**Comment by Devil625** [comment]
pay attention to `self.MAX_SENTENCE_LENGTH =500`

**Comment by qicheng-ma** [comment]
Hi Admin,

I changed the code in data.py and re-trained LSTM:
        self.MAX_SENTENCE_LENGTH =1500 

But I still get the same error:

nbest: 1
Load Model from file:  sample_data_650/lstmcrf
build network...
use_char:  False
word feature extractor:  LSTM
use crf:  True
build word sequence feature extractor: LSTM...
build word representation...
build CRF...
Decode raw data, nbest: 1 ...
Traceback (most recent call last):
  File "../main.py", line 466, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "../main.py", line 422, in load_model_decode
    speed, acc, p, r, f, pred_results, pred_scores = evaluate(data, model, name, data.nbest)
  File "../main.py", line 201, in evaluate
    acc, p, r, f = get_ner_fmeasure(gold_results, pred_results, data.tagScheme)
  File "/mnt/efs/home/stb3865/software/Codon_Optimization/utils/metric.py", line 57, in get_ner_fmeasure
    accuracy = (right_tag+0.0)/all_tag
ZeroDivisionError: float division by zero

Could you please take a look again ?
Thank you!

**Comment by qicheng-ma** [comment]
Hi Admin

Another test sequence length is 1235.
But it still generate an error.

Could you please help me again ?

Thank you!

-----------------------------------------------------
$ head -n 1 CPA.txt
M j
$ tail -1 CPA.txt
X w
$ wc -l CPA.txt
1235 CPA.txt
(base) [stb3865@ip-10-245-41-202 one_test]$ grep -v '#' tt
python  ../main.py --config demo.decode.config
(base) [stb3865@ip-10-245-41-202 one_test]$ bash tt
Seed num: 42
MODEL: decode
CPA.txt
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DATA SUMMARY START:
I/O:
     Tag          scheme: NoSeg
     MAX SENTENCE LENGTH: 1500
     MAX   WORD   LENGTH: -1
     Number   normalized: True
     Word  alphabet size: 23
     Char  alphabet size: 23
     Label alphabet size: 22
     Word embedding  dir: sample_liver_data_650/20coilanino.vector
     Char embedding  dir: None
     Word embedding size: 21
     Char embedding size: 30
     Norm   word     emb: False
     Norm   char     emb: False
     Train  file directory: ensembl101_liver/cboxtrain.txt
     Dev    file directory: ensembl101_liver/cboxdev.txt
     Test   file directory: ensembl101_liver/cboxtest.txt
     Raw    file directory: CPA.txt
     Dset   file directory: lstmcrf.dset
     Model  file directory: sample_liver_data_650/lstmcrf
     Loadmodel   directory: lstmcrf
     Decode file directory: CPA.out
     Train instance number: 4517
     Dev   instance number: 386
     Test  instance number: 477
     Raw   instance number: 0
     FEATURE num: 0
++++++++++++++++++++++++++++++++++++++++
Model Network:
     Model        use_crf: True
     Model word extractor: LSTM
     Model       use_char: False
++++++++++++++++++++++++++++++++++++++++
Training:
     Optimizer: adam
     Iteration: 1
     BatchSize: 32
     Average  batch   loss: False
++++++++++++++++++++++++++++++++++++++++
Hyperparameters:
     Hyper              lr: 0.003
     Hyper        lr_decay: 0.05
     Hyper         HP_clip: None
     Hyper        momentum: 0.0
     Hyper              l2: 1e-08
     Hyper      hidden_dim: 650
     Hyper         dropout: 0.5
     Hyper      lstm_layer: 4
     Hyper          bilstm: True
     Hyper             GPU: True
DATA SUMMARY END.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
nbest: 0
Load Model from file:  sample_liver_data_650/lstmcrf
build network...
use_char:  False
word feature extractor:  LSTM
use crf:  True
build word sequence feature extractor: LSTM...
build word representation...
build CRF...
Decode raw data, nbest: 0 ...
Traceback (most recent call last):
  File "../main.py", line 466, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "../main.py", line 422, in load_model_decode
    speed, acc, p, r, f, pred_results, pred_scores = evaluate(data, model, name, data.nbest)
  File "../main.py", line 201, in evaluate
    acc, p, r, f = get_ner_fmeasure(gold_results, pred_results, data.tagScheme)
  File "/mnt/efs/home/stb3865/software/Codon_Optimization/utils/metric.py", line 57, in get_ner_fmeasure
    accuracy = (right_tag+0.0)/all_tag
ZeroDivisionError: float division by zero

**Comment by qicheng-ma** [comment]
I found the reason, thank you for your help
